# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160721_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default='deadbeeffordad', max_length=17, verbose_name='Mac адрес'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(default='rtsp', max_length=10, verbose_name='Протокол'),
        ),
    ]
