# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160728_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
