# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('rtsp', 'rtsp'), ('http', 'http'), ('rtp', 'rtp')], default='rtsp', max_length=5, verbose_name='Протокол'),
        ),
    ]
